# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mrtask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mrtask.proto',
  package='mapreducetask',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmrtask.proto\x12\rmapreducetask\"\x0e\n\x0cIDemandATask\"\t\n\x07IAmDone\"\x06\n\x04Okay\"h\n\x04Task\x12\x10\n\x08map_task\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12)\n\x08\x66ileinfo\x18\x03 \x03(\x0b\x32\x17.mapreducetask.MetaData\x12\x12\n\ntask_param\x18\x04 \x01(\x05\"C\n\x08MetaData\x12\x11\n\tfileindex\x18\x05 \x01(\x05\x12\x11\n\tstartseek\x18\x06 \x01(\x03\x12\x11\n\tchunksize\x18\x07 \x01(\x03\x32\x83\x01\n\x06MRTask\x12>\n\x08SendTask\x12\x1b.mapreducetask.IDemandATask\x1a\x13.mapreducetask.Task\"\x00\x12\x39\n\x08TaskDone\x12\x16.mapreducetask.IAmDone\x1a\x13.mapreducetask.Okay\"\x00\x62\x06proto3')
)




_IDEMANDATASK = _descriptor.Descriptor(
  name='IDemandATask',
  full_name='mapreducetask.IDemandATask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=45,
)


_IAMDONE = _descriptor.Descriptor(
  name='IAmDone',
  full_name='mapreducetask.IAmDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=56,
)


_OKAY = _descriptor.Descriptor(
  name='Okay',
  full_name='mapreducetask.Okay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=64,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='mapreducetask.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_task', full_name='mapreducetask.Task.map_task', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='mapreducetask.Task.task_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileinfo', full_name='mapreducetask.Task.fileinfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_param', full_name='mapreducetask.Task.task_param', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=170,
)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='mapreducetask.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileindex', full_name='mapreducetask.MetaData.fileindex', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startseek', full_name='mapreducetask.MetaData.startseek', index=1,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunksize', full_name='mapreducetask.MetaData.chunksize', index=2,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=239,
)

_TASK.fields_by_name['fileinfo'].message_type = _METADATA
DESCRIPTOR.message_types_by_name['IDemandATask'] = _IDEMANDATASK
DESCRIPTOR.message_types_by_name['IAmDone'] = _IAMDONE
DESCRIPTOR.message_types_by_name['Okay'] = _OKAY
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDemandATask = _reflection.GeneratedProtocolMessageType('IDemandATask', (_message.Message,), dict(
  DESCRIPTOR = _IDEMANDATASK,
  __module__ = 'mrtask_pb2'
  # @@protoc_insertion_point(class_scope:mapreducetask.IDemandATask)
  ))
_sym_db.RegisterMessage(IDemandATask)

IAmDone = _reflection.GeneratedProtocolMessageType('IAmDone', (_message.Message,), dict(
  DESCRIPTOR = _IAMDONE,
  __module__ = 'mrtask_pb2'
  # @@protoc_insertion_point(class_scope:mapreducetask.IAmDone)
  ))
_sym_db.RegisterMessage(IAmDone)

Okay = _reflection.GeneratedProtocolMessageType('Okay', (_message.Message,), dict(
  DESCRIPTOR = _OKAY,
  __module__ = 'mrtask_pb2'
  # @@protoc_insertion_point(class_scope:mapreducetask.Okay)
  ))
_sym_db.RegisterMessage(Okay)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'mrtask_pb2'
  # @@protoc_insertion_point(class_scope:mapreducetask.Task)
  ))
_sym_db.RegisterMessage(Task)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'mrtask_pb2'
  # @@protoc_insertion_point(class_scope:mapreducetask.MetaData)
  ))
_sym_db.RegisterMessage(MetaData)



_MRTASK = _descriptor.ServiceDescriptor(
  name='MRTask',
  full_name='mapreducetask.MRTask',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=242,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTask',
    full_name='mapreducetask.MRTask.SendTask',
    index=0,
    containing_service=None,
    input_type=_IDEMANDATASK,
    output_type=_TASK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TaskDone',
    full_name='mapreducetask.MRTask.TaskDone',
    index=1,
    containing_service=None,
    input_type=_IAMDONE,
    output_type=_OKAY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MRTASK)

DESCRIPTOR.services_by_name['MRTask'] = _MRTASK

# @@protoc_insertion_point(module_scope)
